[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "model-engine"
version = "0.1.0"
description = "Hybrid phishing URL scoring engine"
authors = [{ name = "PhishSentry" }]
requires-python = ">=3.10"
readme = "README.md"
