[project]
name = "scoring-api"
version = "0.1.0"
description = "PhishSentry scoring API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.110,<0.112",
    "uvicorn[standard]>=0.29,<0.31",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4,<9.0",
    "httpx>=0.26,<0.27",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
